# -*- coding: utf-8 -*-
"""MBARTtranslate_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yl1lXdDhEAUfILMPhu5cT2AD1Oszt2YB

# DL Translate

*A deep learning-based translation library built on Huggingface `transformers` and Facebook's `mBART-Large`*

💻 [GitHub Repository](https://github.com/xhlulu/dl-translate)\
📚 [Documentation](https://git.io/dlt-docs) / [readthedocs](https://dl-translate.readthedocs.io)\
🐍 [PyPi project](https://pypi.org/project/dl-translate/)

## Quickstart

Install the library with pip:
"""

!pip install -q dl-translate

"""To translate some text:"""

import dl_translate as dlt

mt = dlt.TranslationModel()

text_pl = "Poszedłem do domu po spotkaniu."
mt.translate(text_pl, source=dlt.lang.POLISH, target=dlt.lang.ENGLISH)

"""Above, you can see that `dlt.lang` contains variables representing each of the 50 available languages with auto-complete support. Alternatively, you can specify the language (e.g. "Arabic") or the language code (e.g. "fr" for French):"""

text_ar = "Ich habe keine Ahnung wo ist sie."
mt.translate(text_ar, source="German", target="en")

"""If you want to verify whether a language is available, you can check it:"""

print(mt.available_languages())  # All languages that you can use
print(mt.available_codes())  # Code corresponding to each language accepted
print(mt.get_lang_code_map())  # Dictionary of lang -> code

"""## Usage

### Selecting a device

When you load the model, you can specify the device:
```python
mt = dlt.TranslationModel(device="auto")
```

By default, the value will be `device="auto"`, which means it will use a GPU if possible. You can also explicitly set `device="cpu"` or `device="gpu"`, or some other strings accepted by [`torch.device()`](https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.device). __In general, it is recommend to use a GPU if you want a reasonable processing time.__

Let's check what we originally loaded:
"""

mt.device

"""### Loading from a path

By default, `dlt.TranslationModel` will download the model from the [huggingface repo](https://huggingface.co/facebook/mbart-large-50-one-to-many-mmt) and cache it. However, you are free to load from a path:
```python
mt = dlt.TranslationModel("/path/to/your/model/directory/", model_family="mbart50")
```
Make sure that your tokenizer is also stored in the same directory if you use this approach.


### Using a different model

You can also choose another model that has [a similar format](https://huggingface.co/models?filter=mbart-50). In those cases, it's preferable to specify the model family:
```python
mt = dlt.TranslationModel("facebook/mbart-large-50-one-to-many-mmt")
mt = dlt.TranslationModel("facebook/m2m100_1.2B", model_family="m2m100")
```
Note that the available languages will change if you do this, so you will not be able to leverage `dlt.lang` or `dlt.utils`.


### Breaking down into sentences

It is not recommended to use extremely long texts as it takes more time to process. Instead, you can try to break them down into sentences with the help of `nltk`. First install the library with `pip install nltk`, then run:
"""

import nltk
nltk.download("punkt")

text = "Mr. Smith went to his favorite cafe. There, he met his friend Dr. Joe."
sents = nltk.tokenize.sent_tokenize(text, "english")  # don't use dlt.lang.ENGLISH
" ".join(mt.translate(sents, source=dlt.lang.ENGLISH, target=dlt.lang.POLISH))

"""### Setting a `batch_size` and verbosity when calling `dlt.TranslationModel.translate`

It's possible to set a batch size (i.e. the number of elements processed at once) for `mt.translate` and whether you want to see the progress bar or not:
"""

mt.translate(sents, source=dlt.lang.ENGLISH, target=dlt.lang.POLISH, batch_size=32, verbose=True)

"""If you set `batch_size=None`, it will compute the entire `text` at once rather than splitting into "chunks". We recommend lowering `batch_size` if you do not have a lot of RAM or VRAM and run into CUDA memory error. Set a higher value if you are using a high-end GPU and the VRAM is not fully utilized.


### `dlt.utils` module

An alternative to `mt.available_languages()` is the `dlt.utils` module. You can use it to find out which languages and codes are available:

"""

print(dlt.utils.available_languages('mbart50'))  # All languages that you can use
print(dlt.utils.available_codes('mbart50'))  # Code corresponding to each language accepted
print(dlt.utils.get_lang_code_map('mbart50'))  # Dictionary of lang -> code

"""## Advanced

The following section assumes you have knowledge of PyTorch and Huggingface Transformers.

### Saving and loading

If you wish to accelerate the loading time the translation model, you can use `save_obj`:

"""

mt.save_obj("saved_model")

"""
Then later you can reload it with `load_obj`:"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# mt = dlt.TranslationModel.load_obj('saved_model')

"""
**Warning:** Only use this if you are certain the torch module saved in `saved_model/weights.pt` can be correctly loaded. Indeed, it is possible that the `huggingface`, `torch` or some other dependencies change between when you called `save_obj` and `load_obj`, and that might break your code. Thus, it is recommend to only run `load_obj` in the same environment/session as `save_obj`. **Note this method might be deprecated in the future once there's no speed benefit in loading this way.**


### Interacting with underlying model and tokenizer

When initializing `model`, you can pass in arguments for the underlying BART model and tokenizer (which will respectively be passed to `MBartForConditionalGeneration.from_pretrained` and `MBart50TokenizerFast.from_pretrained`):

```python
mt = dlt.TranslationModel(
    model_options=dict(
        state_dict=...,
        cache_dir=...,
        ...
    ),
    tokenizer_options=dict(
        tokenizer_file=...,
        eos_token=...,
        ...
    )
)
```

You can also access the underlying `transformers` model and `tokenizer`:"""

bart = mt.get_transformers_model()
tokenizer = mt.get_tokenizer()

print(tokenizer)
print(bart)

"""See the [huggingface docs](https://huggingface.co/transformers/master/model_doc/mbart.html) for more information.


### `bart_model.generate()` keyword arguments

When running `mt.translate`, you can also give a `generation_options` dictionary that is passed as keyword arguments to the underlying `bart_model.generate()` method:
"""

mt.translate(
    sents,
    source=dlt.lang.ENGLISH,
    target=dlt.lang.POLISH,
    generation_options=dict(num_beams=5, max_length=128)
)